name = "Create Adventures"
author = "Cristhian"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eee2e79446c794cbbab9ef5efdf005ca3f3358c8e37222c11142b604fcc8a954"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
