name = "Create Adventures"
author = "Cristhian"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef95b13f6791610fec55d59b5c92190e9e0583caa9de5b4c45421632a145a7f5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
