name = "Create Adventures"
author = "Cristhian"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37ca21eeef26213bb5b3977b896418272d056a317997749ef68e2d9fe531754c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
